
default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: localhost
  username: postgres
  password: root

development:
  <<: *default
  database: deidara_store_development


test:
  <<: *default
  database: deidara_store_test


production:
  <<: *default
  database: deidara_store_production
  username: deidara_store
  password: <%= ENV['EAT_THEN_DATABASE_PASSWORD'] %>